version: '3'
networks:
  mynetwork:
    driver: bridge

services:

  master-data-service:
    container_name: master-data-service
    image: "koko120/master-data-service:latest"
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - mynetwork

  consignment-service:
    container_name: consignment-service
    image: "koko120/consignment-service:latest"
    ports:
      - "8001:8001"
    depends_on:
      - database
    networks:
      - mynetwork
  
  accounts-service:
    container_name: accounts-service
    image: "koko120/accounts-service:latest"
    ports: 
      - "8002:8002"
    depends_on:
      - database
    networks:
      - mynetwork

  mail-service:
    container_name: mail-service
    image: "koko120/mail-service:latest"
    depends_on:
      - database
    networks:
      - mynetwork

  database:
    image: "koko120/database:latest"
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: test_pass
    ports:
      - "3306:3306"
    depends_on:
      - rabbitMQ
    networks:
      - mynetwork

  
  rabbitMQ:
    container_name: rabbitMQ
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
    networks:
      - mynetwork

  

