apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-data-service
  labels:
    app: master-data-service
spec:
  selector:
    matchLabels:
      app: master-data-service
  replicas: 1
  template:
    metadata:
      labels:
        app: master-data-service
    spec:
      containers:
        - name: app
          image: koko120/master-data-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: master-data-service
spec:
  selector:
    app: master-data-service
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
